micronaut:
  application:
    name: testing-app

  router:
    static-resources:
      default:
        enabled: true
        mapping: "/public/**"
        paths: "classpath:public"

  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
    session:
      enabled: true
      login-success-target-url: /home/profile
      login-failure-target-url: /home/authFailed
      logout-success-target-url: /home/login

    intercept-url-map:
      - pattern: /public/**
        http-method: GET
        access:
          - isAnonymous()



hibernate:
  hbm2ddl:
    auto: update
    #schema_filter_provider: goloca.hibernate.CustomSchemaProvider
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
    #region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
  pooled: true
  jmxExport: true
  driverClassName: org.postgresql.Driver
  url: "jdbc:postgresql://localhost:5432/testdb"
  username: "postgres"
  password: "root"

